// login request
export const REQUEST_TO_LOGIN = "REQUEST_TO_LOGIN";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

// register request
export const GET_ALL_USERNAMES = "GET_ALL_USERNAMES";
export const REQUEST_TO_REGISTER = "REQUEST_TO_REGISTER";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";

// lobby request
export const UPDATE_ONLINE_PLAYERS = "UPDATE_ONLINE_PLAYERS";



export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_NON_EXIST_USER_FAILURE = "LOGIN_NON_EXIST_USER_FAILURE";
export const LOGIN_INVALID_PASSWORD_FAILURE = "LOGIN_INVALID_PASSWORD_FAILURE";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const LOGOUT = "LOGOUT";

export const SIGN_UP_ADD_FAILURE = "SIGN_UP_ADD_FAILURE";
export const ADD_TIME_ID = "ADD_TIME_ID";
export const CLEAN_TIME_ID = "CLEAN_TIME_ID";
export const SET_STATUS = "SET_STATUS";
export const SET_PAGE = "SET_PAGE";
export const STORE_USER_LIST = "STORE_USER_LIST";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_GAME_MINES = "SET_GAME_MINES";
export const SET_GAME_BOARD = "SET_GAME_BOARD";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const SET_CONNECTED = "SET_CONNECTED";
export const SET_ALL_MESSAGES = "SET_ALL_MESSAGES";
export const SET_CLIENT_ID = "SET_CLIENT_ID";
export const SET_GAME_PAIR = "SET_GAME_PAIR";