// login request
export const REQUEST_TO_LOGIN = "REQUEST_TO_LOGIN";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT = "LOGOUT";
export const SET_ONBOARDING_STATUS = "SET_ONBOARDING_STATUS";

// register request
export const GET_ALL_USERNAMES = "GET_ALL_USERNAMES";
export const REQUEST_TO_REGISTER = "REQUEST_TO_REGISTER";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";

// lobby request
export const UPDATE_ONLINE_PLAYERS = "UPDATE_ONLINE_PLAYERS";
export const INVITATION_SEND_TO_SERVER = "INVITATION_SEND_TO_SERVER";
export const RECEIVE_INVITATION = "RECEIVE_INVITATION";
export const WAIT_FOR_RESPONSE = "WAIT_FOR_RESPONSE";
export const INVITATION_ACCEPTED = "INVITATION_ACCEPTED";
export const INVITATION_DECLINED = "INVITATION_DECLINED";
export const CLOSE_INVITATION = "CLOSE_INVITATION";
export const UPDATE_PLAYERS = "UPDATE_PLAYERS";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

// game update
export const UPDATE_WIN = "UPDATE_WIN";
export const UPDATE_LOSE = "UPDATE_LOSE";



export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_NON_EXIST_USER_FAILURE = "LOGIN_NON_EXIST_USER_FAILURE";
export const LOGIN_INVALID_PASSWORD_FAILURE = "LOGIN_INVALID_PASSWORD_FAILURE";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";


export const SIGN_UP_ADD_FAILURE = "SIGN_UP_ADD_FAILURE";
export const ADD_TIME_ID = "ADD_TIME_ID";
export const CLEAN_TIME_ID = "CLEAN_TIME_ID";
export const SET_STATUS = "SET_STATUS";
export const SET_PAGE = "SET_PAGE";
export const STORE_USER_LIST = "STORE_USER_LIST";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_GAME_MINES = "SET_GAME_MINES";
export const SET_GAME_BOARD = "SET_GAME_BOARD";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const SET_CONNECTED = "SET_CONNECTED";
export const SET_ALL_MESSAGES = "SET_ALL_MESSAGES";
export const SET_CLIENT_ID = "SET_CLIENT_ID";
export const SET_GAME_PAIR = "SET_GAME_PAIR";