// login request
export const REQUEST_TO_LOGIN = "REQUEST_TO_LOGIN";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT = "LOGOUT";
export const SET_ONBOARDING_STATUS = "SET_ONBOARDING_STATUS";
export const SET_PAGE = "SET_PAGE";

// register request
export const GET_ALL_USERNAMES = "GET_ALL_USERNAMES";
export const REQUEST_TO_REGISTER = "REQUEST_TO_REGISTER";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";

// lobby request
export const UPDATE_ONLINE_PLAYERS = "UPDATE_ONLINE_PLAYERS";
export const INVITATION_SEND_TO_SERVER = "INVITATION_SEND_TO_SERVER";
export const RECEIVE_INVITATION = "RECEIVE_INVITATION";
export const WAIT_FOR_RESPONSE = "WAIT_FOR_RESPONSE";
export const INVITATION_ACCEPTED = "INVITATION_ACCEPTED";
export const INVITATION_DECLINED = "INVITATION_DECLINED";
export const CLOSE_INVITATION = "CLOSE_INVITATION";
export const UPDATE_PLAYERS = "UPDATE_PLAYERS";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

// game update
export const UPDATE_WIN = "UPDATE_WIN";
export const UPDATE_LOSE = "UPDATE_LOSE";
export const GAME_OVER = "GAME_OVER";
export const SET_STATUS = "SET_STATUS";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_GAME_MINES = "SET_GAME_MINES";
export const SET_GAME_BOARD = "SET_GAME_BOARD";
export const SET_GAME_PAIR = "SET_GAME_PAIR";
export const SET_GAME_COLOR = "SET_GAME_COLOR";
export const SET_GAME_PAIR_COLOR = "SET_GAME_PAIR_COLOR";